name: poco_hackers_app
description: "Pocohakers' project"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  cupertino_icons: ^1.0.8
  go_router: ^14.6.0
  google_maps_flutter: ^2.10.0
  http: ^1.2.2
  json_annotation: ^4.9.0

  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.0

  flutter_lints: ^4.0.0

build_runner: ^2.4.6
json_serializable: ^6.6.1

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true